name: Populate Cache

description: |
  An action to populate the gradle cache, if no cache exists.

runs:
  using: composite

  steps:
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'
        cache: 'gradle'
      id: setup

    - name: Populate Cache
      if: ${{ steps.setup.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        ./gradlew --no-daemon build

    - name: Cancel Build
      if: ${{ failure() }}
      uses: andymckay/cancel-action@0.3