name: Populate Cache

description: |
  An action to populate the gradle cache, if no cache exists.

env:
  JAVA_VERSION: 25

runs:
  using: composite

  steps:
    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v5
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: 'gradle'
      id: setup

    - name: Populate Cache
      if: ${{ steps.setup.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        ./gradlew --no-daemon build

    - name: Cancel Build
      if: ${{ failure() }}
      uses: andymckay/cancel-action@0.3