name: Run Integration Tests

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - 'localdeployment/docker-compose.yml'
  pull_request:
    paths:
      - 'localdeployment/docker-compose.yml'

concurrency:
  group: "workflow = ${{ github.workflow }}, ref = ${{ github.event.ref }}, pr = ${{ github.event.pull_request.id }}"
  cancel-in-progress: ${{ github.event_name == 'pull_request' || github.repository != 'chehl/chameleon' }}

permissions:
  actions: write
  checks: write
  pull-requests: write

jobs:
  recreate-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Publish Report
        uses: turing85/publish-report@v2
        with:
          checkout: 'true'
          recreate-comment: true

  populate-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Populate cache
        uses: ./.github/actions/populate-cache

  integration-tests:
    runs-on: ubuntu-latest

    needs:
      - recreate-comment
      - populate-cache

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/integration-test